services:
  - type: web
    name: icon-creator
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: icon-creator-disk
      mountPath: /opt/render/project/src/temp
      sizeGB: 1